
package gui;

import java.awt.Frame;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import output.FileSpectrumOutputModule;
import output.NetworkSpectrumOutputModule;

/**
 * Dialog for the settings of the Beat Analyser.
 * 
 * @author  Stefan Marks
 * @version 1.0 - 15.06.2013: Created
 */
public class PreferencesDialog extends javax.swing.JDialog
{
    public static enum UserChoice
    {
        CLOSE, CANCEL, ACCEPT;
    }
    
    /**
     * Creates a new preferences dialog.
     * 
     * @param parent   the parent frame
     * @param settings the settings to represent
     */
    public PreferencesDialog(Frame parent)
    {
        super(parent, true);
        initComponents();
        pack();
        setLocationRelativeTo(parent);
    }
    
    public UserChoice showDialog()
    {
        userChoice = UserChoice.CLOSE;
        setVisible(true);
        return userChoice;
    }
    
    public void loadFileOutputSettings(FileSpectrumOutputModule output)
    {
        chkEnableLogfileOutput.setSelected(output.isEnabled());
        txtOutputFilename.setText(output.getOutputFilename());
    }

    public void applyFileOutputSettings(FileSpectrumOutputModule output)
    {
        output.setEnabled(chkEnableLogfileOutput.isSelected());
        output.setOutputFilename(txtOutputFilename.getText());
    }
    
    public void loadNetworkOutputSettings(NetworkSpectrumOutputModule output)
    {
        chkEnableNetworkOutput.setSelected(output.isEnabled());
        txtNetworkAddress.setText(output.getTargetAddress());
    }

    public void applyNetworkOutputSettings(NetworkSpectrumOutputModule output)
    {
        output.setEnabled(chkEnableNetworkOutput.isSelected());
        output.setTargetAddress(txtNetworkAddress.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTabs = new javax.swing.JTabbedPane();
        pnlFileOutput = new javax.swing.JPanel();
        javax.swing.JLabel lblEnableFileOutput = new javax.swing.JLabel();
        chkEnableLogfileOutput = new javax.swing.JCheckBox();
        javax.swing.JLabel lblOutputFilename = new javax.swing.JLabel();
        txtOutputFilename = new javax.swing.JTextField();
        pnlNetworkOutput = new javax.swing.JPanel();
        javax.swing.JLabel lblEnableNetworkOutput = new javax.swing.JLabel();
        chkEnableNetworkOutput = new javax.swing.JCheckBox();
        javax.swing.JLabel lblNetworkAddress = new javax.swing.JLabel();
        txtNetworkAddress = new javax.swing.JTextField();
        javax.swing.JPanel pnlButtons = new javax.swing.JPanel();
        javax.swing.JButton btnCancel = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Preferences");

        panelTabs.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelTabs.setPreferredSize(new java.awt.Dimension(400, 300));

        pnlFileOutput.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlFileOutput.setLayout(new java.awt.GridBagLayout());

        lblEnableFileOutput.setText("Enable Logfile Output:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        pnlFileOutput.add(lblEnableFileOutput, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        pnlFileOutput.add(chkEnableLogfileOutput, gridBagConstraints);

        lblOutputFilename.setText("Filename:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 6);
        pnlFileOutput.add(lblOutputFilename, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        pnlFileOutput.add(txtOutputFilename, gridBagConstraints);

        panelTabs.addTab("File Output", pnlFileOutput);

        pnlNetworkOutput.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        pnlNetworkOutput.setLayout(new java.awt.GridBagLayout());

        lblEnableNetworkOutput.setText("Enable Network Output:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
        pnlNetworkOutput.add(lblEnableNetworkOutput, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        pnlNetworkOutput.add(chkEnableNetworkOutput, gridBagConstraints);

        lblNetworkAddress.setText("Target Address/Port:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 6);
        pnlNetworkOutput.add(lblNetworkAddress, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        pnlNetworkOutput.add(txtNetworkAddress, gridBagConstraints);

        panelTabs.addTab("Network Output", pnlNetworkOutput);

        getContentPane().add(panelTabs, java.awt.BorderLayout.CENTER);

        pnlButtons.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.TRAILING));

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });
        pnlButtons.add(btnCancel);

        btnAccept.setText("Accept");
        btnAccept.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAcceptActionPerformed(evt);
            }
        });
        pnlButtons.add(btnAccept);

        getContentPane().add(pnlButtons, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        userChoice = UserChoice.CANCEL;
        setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAcceptActionPerformed
    {//GEN-HEADEREND:event_btnAcceptActionPerformed
        userChoice = UserChoice.ACCEPT;
        setVisible(false);
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JCheckBox chkEnableLogfileOutput;
    private javax.swing.JCheckBox chkEnableNetworkOutput;
    private javax.swing.JTabbedPane panelTabs;
    private javax.swing.JPanel pnlFileOutput;
    private javax.swing.JPanel pnlNetworkOutput;
    private javax.swing.JTextField txtNetworkAddress;
    private javax.swing.JTextField txtOutputFilename;
    // End of variables declaration//GEN-END:variables

    private UserChoice userChoice;
}
